Fix for dependency error
With the current dependency the container is failing due to a Flask dependency error.

ImportError: cannot import name 'escape' from 'jinja2'